spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springsecurity
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 8080

mybatis:
  mapper-location: classpath:mybatis/**/*.xml

